### ISSUE TITLE
failing when running in docker

### ISSUE THREAD

**Issue by mmmmmrob** [nathanboktae/mocha-casperjs#101]
Hi, I'm getting a fail when trying to run mocha-casperjs in docker, though I'm not sure it's docker related.

```npm info it worked if it ends with ok
npm info using npm@3.8.6
npm info using node@v5.11.0
npm info lifecycle myapp@0.0.0~premc: myapp@0.0.0
npm info lifecycle myapp@0.0.0~mc: myapp@0.0.0

> myapp@0.0.0 mc /app
> mocha-casperjs test/integration/google.js

I'm `fs` modules
TypeError: undefined is not a function (evaluating 'fs.exists('mocha-casperjs.opts')')

  phantomjs://code/cli.js:11 in global code
  :0 in injectJs
  phantomjs://code/bootstrap.js:435
^C```

You can see from ^C is hangs at that point.

Any ideas?

**Comment by nathanboktae** [comment]
What version of phantomjs are you using?

**Comment by mmmmmrob** [comment]
"phantomjs-prebuilt": "^2.1.7",

**Comment by mmmmmrob** [comment]
The problem is not docker related, it happens running locally on my mac too, not just in the docker container

**Comment by mmmmmrob** [comment]
This issue was down to a spurious reference to 'fs' that had crept into my packages.json through a typo.

The fs package in npm is a stopword/placeholder and causes the built-in fs package to not to be used, hence breaking.

My bad, sorry for the confusion.
