### ISSUE TITLE
Whatever command I run using mocha-casperjs, it errors

### ISSUE THREAD

**Issue by dbaronov** [nathanboktae/mocha-casperjs#105]
Have set up my enviro to use CasperJS with Mocha and Chai and PhantomJS . Then while trying to run something like "mocha-casperjs test/test-index.js" I get an error:

`/c/Program Files/nodejs/node_modules/mocha-casperjs/bin/mocha-casperjs: line 42: /c: Is a directory`

In fact even if I try to run "mocha-casperjs" I get the same error.

Please advise on what I might be doing wrong.

**Comment by nathanboktae** [comment]
See the readme section for Windows users - you need to use `mocha-jasperjs.bat`
