### ISSUE TITLE
How can I setup proxy for casperjs?

### ISSUE THREAD

**Issue by dickeylth** [nathanboktae/mocha-casperjs#50]
Thank you for your nice module first!

Now I encounted a problem that I need to setup proxy for casperjs, is it possible?

Besides, is it possilbe to integrate code coverage tools like istanbul with this module?

Thank you again!

**Comment by nathanboktae** [comment]
Yes you can add phantomjs and casperjs parameters and mocha-casperjs will just pass them through. So you can pass through `--proxy` and [other proxy parameters](http://phantomjs.org/api/command-line.html) to phantomjs

`mocha-casperjs` doesn't provide any code coverage integration hooks, but it's not stopping you either - it's a separate concern. However unless you're testing a single page app, you will need to instrument and scrape the coverage results before the end of a page navigation, and then take the results and aggregate them in a meaningful way. that's more of a `casperjs` level integration, and if you or someone that builds that module can just include it from code or casperjs command line that also includes mocha-casperjs in the style of `casperjs my-coverage-module.js node_modules/mocha-casperjs/bin/cli.js`

**Comment by haisamhameed** [comment]
I am still stuck i have casperjs script to scrape a website .. Script is running perfect. But the thing is i want to use switchproxy then hit to URL but i can't figure it out .. If you guys help me will be very thankful to you
