### ISSUE TITLE
done() called multiple times

### ISSUE THREAD

**Issue by scottlabs** [nathanboktae/mocha-casperjs#51]
We're running a fairly extensive testing framework on top of CasperJS and Mocha. We've encapsulated reusable functionality into functions (say, users.create() to create a user) so as to make it easier to write tests, along with keep the testing framework up to date as things change.

One issue I continuously run into is that a single failing test will incorrectly report back "done()  called multiple times", and generally cause cascading failures on subsequent tests. I finally hunted it down today.

This is what we're doing, and this will cause the error:

```
describe('Foo', function() {
    it('should foo', function(done) {
        function foo(callback) {
            casper.then(function() {
                throw Error('dum dum');
            });

            casper.then(function() {
                callback();
            });
        };

        foo(function() {
            console.log('we callback');
            done();
        });
    });

    it('should bar', function(done) {
        setTimeout(function() {
            done();
        }, 3000);
    });
});
```

The first test executes, and throws an error. However, CasperJS still has another step on its stack, which gets executed, which then throws the `multiple done()s` error.

This also only works for me with the second test, as Mocha still needs to be running for this error to occur. Otherwise, the test suite finishes and it reports the failure correctly. Which was causing me to pull my hair out, since it seemed to be so intermittent!

A hacky solution is to, in the 'done' function of mocha.js, clear any casper steps. But this obviously doesn't work long term.

**Comment by scottlabs** [comment]
I opened a pull request to illustrate what works for my test case, though this would break if someone were to build a test suite that somehow relied on casper then()s to be run after a failing test. I'm not sure what that would look like, since in my case casper then()s only get added on every test execution.

**Comment by nathanboktae** [comment]
So in the case of 'should foo', since you have casper steps, mocha-casperjs is the master for telling mocha when the test is done. Could you elaborate on why you would also want to call done explicitly instead of doing:

```javascript
it('should foo', function() {
  function foo(callback) {
    casper.then(function() {
      throw Error('dum dum');
    });

    casper.then(function() {
      callback();
    });
  }

  foo(function() {
    console.log('we callback');
  });
});
```

consider a regular mocha test:

```javascript
it('does multiple async stuff', function(done) {
  setTimeout(function() {
    1.should.not.be.ok
  }, 200)

  setTimeout(function() {
    2.should.be.ok()
    // since we failed earlier, we'll get the 'done() called multiple times' error
    done()
  }, 400)
})
```

I'm asking your scenario, as mocha-casperjs explicitly clearing any pending steps could be desired. given how stateful they are, conditionally running steps seems to make test writing even more complicated.

**Comment by scottlabs** [comment]
Ah, I didn't realize that was the case. I'm coming from a unit testing background with mocha so just carried over the habit of calling done() explicitly.

I tested as you specified and yes, that resolves my issue. Thanks for the prompt reply Nathan, and cheers on a solid module!

**Comment by nathanboktae** [comment]
Good to hear! It made me happy to hear you have `fairly extensive testing framework` built on this!

**Comment by scottlabs** [comment]
Absolutely. And other than this issue (which turns out to be user error) everything is working swimmingly.
