### ISSUE TITLE
Catch HTTP status code

### ISSUE THREAD

**Issue by MalcolmK** [nathanboktae/mocha-casperjs#54]
Hey,

In CasperJS it is possible to [add handlers for http status codes](http://docs.casperjs.org/en/latest/modules/casper.html#httpstatushandlers). But I'm not sure how to do this when using mocha-casperjs, because you are not creating a new casper object.

Regards,

Malcolm Kindermans

**Comment by nathanboktae** [comment]
Can you not add your handlers to `casper.options.httpStatusHandlers` before any test runs?

**Comment by nathanboktae** [comment]
Reopen if setting `casper.options.httpStatusHandlers` doesn't work for you.
