### ISSUE TITLE
Issue with multiple failing assertions interfering with test results

### ISSUE THREAD

**Issue by scottlabs** [nathanboktae/mocha-casperjs#55]
Hi Nathan, I wanted to follow up on something you mentioned in https://github.com/nathanboktae/mocha-casperjs/issues/51 about clearing pending steps.

Let's say we've got multiple assertions in a test, something that looks like this:

```    
    describe.only('one success and two failures', function() {
        it('this should only fail once', function() {
            casper.thenOpen('http://localhost/foo', function() {
                '1'.should.equal('2');
            });
            casper.then(function() {
                console.log('should not get here!');
                '3'.should.equal('4');
            });
        });

        it('should pass here', function() {
            casper.then(function() {
                '1'.should.equal('1');
            });
        });

        it('should fail here', function() {
            casper.then(function() {
                '1'.should.equal('2');
            });
        });
    });

```

This causes three failures, with the second test incorrectly reporting the failure from the first test.

Is there any way to clear pending casper steps, within a test? It looks like the casper step stack includes every casper step across every test and there's no way to distinguish steps specific to a test.

Obviously one way around the above is to avoid multiple assertions in tests but we're also doing a fair amount of teardown in tests (which can in turn throw errors if data isn't in the right state, and those errors then cascade). Curious if you've ever run into this or best practices how to get around it.

**Comment by nathanboktae** [comment]
Great report! No I've run into it alot, and it's the bane of this project as in a way, both casper and mocha want to control the flow of things. They both have a list of things to do (steps and tests), hooks they fire that can fail, the things to do can fail, can be skipped, and both have different timeouts.

> Is there any way to clear pending casper steps, within a test?

Rather than doing that, `mocha-casperjs` could run all the steps for a test and aggregate the failures.

> Obviously one way around the above is to avoid multiple assertions in tests but we're also doing a fair amount of teardown in tests (which can in turn throw errors if data isn't in the right state, and those errors then cascade). Curious if you've ever run into this or best practices how to get around it.

Yeah unlike traditional unit tests, there's a lot of state on the browser side so it is natural to do a lot of assertions in one go. I have often done the action in a `before` block (e.g. navigate to a view, fill and submit a form) then done assertions or smaller actions (test your client side validation that you get an invalid message) in a test. But I think what you are doing is fine. This is a bug in `mocha-casperjs` and it should handle it.

**Comment by scottlabs** [comment]
Ah ok, thanks for the explanation, I understand. That'd be awesome if it could aggregate all failures into one test failure object that gets passed to the reporter.

**Comment by scottlabs** [comment]
`npm test` is reporting failures, so this is more of a proposal than something that's mergeable, but here's something:

https://github.com/nathanboktae/mocha-casperjs/pull/56

This adds a check in the `failTest` function to see if additional casper steps exist. I'm not sure if this is the kosher way to do it, but it correctly works for something like the below:

```
'use strict';
casper.start('http://localhost');
describe('Debugger Script', function() {
    it('should fail a first time', function() {
        casper.then(function() {
            '1'.should.equal('2');
        });
        casper.then(function() {
            '1'.should.equal('3');
        });
        casper.then(function() {
            '1'.should.equal('1');
        });
    });
    it('should pass a first time', function() {
        casper.then(function() {
            '1'.should.equal('1');
        });
    });
    it('should fail a second time', function() {
        casper.then(function() {
            '1'.should.equal('32');
        });
    });
    it('should fail a third time', function() {
        casper.then(function() {
            '1'.should.equal('2');
        });
        casper.then(function() {
            '3'.should.equal('4');
        });
        casper.then(function() {
            '3'.should.equal('5');
        });
    });

    it('should pass a second time', function() {
        casper.then(function() {
            '1'.should.equal('1');
        });
    });
});
```

Like I said, not sure if this would be the best way to tackle, what do you think?

**Comment by nathanboktae** [comment]
Closing since #56 was merged.
