### ISSUE TITLE
Configure phantomjs options

### ISSUE THREAD

**Issue by fain182** [nathanboktae/mocha-casperjs#57]
I need to run some test giving the `ssl-protocol` configuration option to phantomjs.

Actually i could fix temporarily the problem modifing the https://github.com/nathanboktae/mocha-casperjs/blob/master/bin/mocha-casperjs#L36

```
$mcPath/../../casperjs/bin/casperjs --ssl-protocol=any $mcPath/cli.js --mocha-casperjs-path=$mcPath/.. $*
```

But this is obviously a bad solution because I should not change a file of mocha-casperjs, which is the right way to do it?

**Comment by nathanboktae** [comment]
It will pass all the way through to phantomjs. `$*` passes all command line options through, then `casperjs` will pass `ssl-protocol` through [here](https://github.com/n1k0/casperjs/blob/f23e383376422ca9c2ecab1395e9e51e8eb9992b/bin/casperjs#L33)

Are you saying it doesn't work? did you try it?

**Comment by fain182** [comment]
thanks, it worked!
Maybe we could add it to the documentation? It seems to me that this information is missing.
