### ISSUE TITLE
'/bin/sh' is not recognized 

### ISSUE THREAD

**Issue by FierstArter** [nathanboktae/mocha-casperjs#60]
I'm just trying to run the google testing demo in the demo and I'm having absolutely no luck. I can't even call the --help option.

I've tried installing locally and globally
mocha
casperjs
mocha-casperjs
chai
casper-chai
phantomjs

I'm still pretty new to this whole node thing, so maybe I missed installing something?

Running Windows 7 x 64

**Comment by nathanboktae** [comment]
are you using `mocha-casperjs.bat` that's included instead of just `mocha-casperjs` ? Also npm + cygwin is a world if pain so don't do that if that is your situation.

**Comment by FierstArter** [comment]
Ok, I think I got what you're talking about but I'm a little confused if this is how I'm suppose to be calling it.

I went into node_modules/mocha-casperjs/bin and ran the mocha-casperjs.bat. It ran fine but it needed a test folder. Which, no problem, I just put the script in there and it worked fine.

I was under the impression that I should be calling mocha-casperjs from the top level? Is this not the case?

**Comment by nathanboktae** [comment]
See issue #25

> Also, I'm getting some pretty weird reporting 

Yeah because none of Microsoft's 10,000 developers on Windows took time in the pass 15 years to add proper color code support to the terminal. You can disable color via `-C`, or use a 3rd party console like https://github.com/cbucher/console.

**Comment by FierstArter** [comment]
You the man! Thanks for your help.
