### ISSUE TITLE
Use commander.js

### ISSUE THREAD

**Issue by denar90** [nathanboktae/mocha-casperjs#78]
@nathanboktae can we use [commander.js](https://github.com/tj/commander.js) instead of defining commands in `sh` script?

**Comment by nathanboktae** [comment]
No, we can't. The commands are not defined in the shell script, they are processed directly by `mocha-casperjs` which runs in PhantomJS, not Node.js. there is no node code I'm this project. npm is just used as a distribution mechanism.
