### ISSUE TITLE
Trouble getting things working; the system can not find the file specified, did you install phantomjs?

### ISSUE THREAD

**Issue by hughlomas** [nathanboktae/mocha-casperjs#79]
Sorry, this is more of a support request than an issue with the package.

I'm on Windows 8.1. I went through the installation and I'm encountering problems when trying to run mocha-casperjs.bat. I've tried to troubleshoot things but I'm having difficulty determining the problem and I can't find any similar issues or posts. 

![image](https://cloud.githubusercontent.com/assets/187210/12825436/47947698-cb44-11e5-9198-3fb9e5da32f7.png)

Do you have any idea how to correct that?

**Comment by nathanboktae** [comment]
Is it not using `casperjs.exe` to startup on windows? that's what [the `.bat` file uses...](https://github.com/nathanboktae/mocha-casperjs/blob/a25a8b6e0540ee7323e5cba7ae6961e3a246149b/bin/mocha-casperjs.bat#L36) not sure how you end up calling `bootstrap.js` .

You do need phantomjs installed globally as #76 pointed out - if you want to fix the `.bat` file and send a PR, that'd be great (I don't use Windows anymore).

**Comment by nathanboktae** [comment]
If you still need help ask a question [on Gitter](https://gitter.im/nathanboktae/mocha-casperjs)
