### ISSUE TITLE
ReferenceError: Can't find variable: assert

### ISSUE THREAD

**Issue by brandonros** [nathanboktae/mocha-casperjs#86]
Right out of the gate, I was expecting "assert" to be defined.

This is common with Mocha, no? Do I need to require it, or is that not supported?

**Comment by nathanboktae** [comment]
> Right out of the gate, I was expecting "assert" to be defined.

Why do you expect that? Mocha doesn't come with an assertion library.

`mocha-casperjs` will look for `chai` and `casper-chai` if you have installed them. This is explained [in the readme](https://github.com/nathanboktae/mocha-casperjs#additional-conveniences)
