### ISSUE TITLE
Test No Longer Passes

### ISSUE THREAD

**Issue by dschinkel** [nathanboktae/mocha-casperjs#92]
I spent 2 hours looking at this with no luck.

I've got a situation where now, the same test, same code will not pass.  You run localhost:3000 and the text that fetchText was checking is there, but for some reason, it's failing, even though that text is there in the browser.

This is a test that was working fine, and the same text has been rendered to that page for a long time now.  For some reason casper.fetchText('h3') is returning an empty string whereas yesterday it was working fine.

I've shared my code to you Nathan, so that you may clone and run it.  Just type gulp at the command-line to run it and you will see what I'm referring to.

https://github.com/dschinkel/we-do-tdd

**Comment by dschinkel** [comment]
it's an issue with my bundle.  My Gulp tasks aren't truly running in sequence, the start server is happening before the bundle.js file is being created on the file system still.  I'll resolve it, probably not an issue with mocha-casper so closing this.

**Comment by dschinkel** [comment]
this is still a problem.  Check out my latest code in that repo...

**Comment by nathanboktae** [comment]
Are you using windows?

**Comment by dschinkel** [comment]
no OS X

**Comment by nathanboktae** [comment]
> For some reason casper.fetchText('h3') is returning an empty string whereas yesterday it was working fine.

Then it's a regression in casperjs or a legitimate test breakage.

**Comment by dschinkel** [comment]
well it was passing a while back so...doesn't make sense.  I'll keep looking at it but nothing seems to stick out as to why now it's not passing when the text is on that page.

**Comment by dschinkel** [comment]
well or... maybe, your'e right, wtf!  I just tried an npm update which I hadn't tried in a long time

$ npm update
npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "update"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: casperjs@'>=1.1.0 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.1.0-beta2, 1.1.0-beta3, 1.1.0-beta4, 1.1.0-beta5
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dave/code/projects/we-do-tdd/npm-debug.log

**Comment by dschinkel** [comment]
So do I need to just install mocha-casperjs only? Do I need also npm install --save-dev casper and/or npm install --save-dev casperjs?

**Comment by dschinkel** [comment]
well the npm install issue is fixed https://github.com/n1k0/casperjs/issues/1525

still working on figuring out why my tests isn't passing.

**Comment by dschinkel** [comment]
Christ, the problem is that since I'm rendering a react component, it's rendered to the DOM as <h3 data-reactid=".0.0">``` which is why my test is failing.   When I try hard coding it into my index.html as ```<h3>No Companies found</h3>``` it works again.  Errr...

**Comment by dschinkel** [comment]
this is where it all started btw https://github.com/n1k0/casperjs/issues/1527 <https://github.com/n1k0/casperjs/issues/1527> IMO his attitude went downhill and pissed me off toward the middle.

**Comment by dschinkel** [comment]
it may be a timing issue, looking into it...I'll report back later.

**Comment by dschinkel** [comment]
I appreciate your support Nathan, unlike what I got over at the Casper site.
