### ISSUE TITLE
Add more options to mocha-casper.opts

### ISSUE THREAD

**Issue by windkomo** [nathanboktae/mocha-casperjs#95]
I noticed the mocha-casperjs.opts file behaved differently from the mocha.opts file :

- Mocha looks for the opts file in the `/test` directory
- Mocha allows specifying a opts file path: `mocha --opts test/unit/mocha.opts`

Whereas mocha-casperjs.opts must be in the current directory or it won't be found (unless I'm mistaken).

Also, mocha.opts allows specifying a test directory where to look for test files:
mocha.opts:
`test/unit`

Any opinion ?

**Comment by nathanboktae** [comment]
Yup these both sound like great improvements.

**Comment by windkomo** [comment]
Thanks for the fast input, I'll try to submit a PR this week or so !

**Comment by nathanboktae** [comment]
Great, looking forward to it :)

**Comment by payaaam** [comment]
Will this include the ability to specifcy the `--recursive` flag?

**Comment by windkomo** [comment]
I'll try, at least :)

**Comment by nathanboktae** [comment]
> Will this include the ability to specifcy the --recursive flag?

This is tracked in #20 and a bit bigger work item because you need a walk implementation that runs in phantomjs. I'd do that as separate PR.

> mocha-casperjs is freezing or just not finding test files when I specify a folder with multiple tests in it.

sounds like a separate issue.

**Comment by windkomo** [comment]
@nathanboktae I submitted a PR, looking forward to feedback :)
