### ISSUE TITLE
Test all files from other then test or tests folder on windows

### ISSUE THREAD

**Issue by ambrt** [nathanboktae/mocha-casperjs#97]
I can run multiple tests from 'test' folder correctly.
But when i specify path to other folder the tests aren't executed.

i tried

> mocha-casperjs.bat test-mocha-casperjs/test/*.js

and

> mocha-casperjs.bat test-mocha-casperjs/test/

I'm on windows and using normal command line prompt

**Comment by nathanboktae** [comment]
You probably need `test-mocha-casperjs\test` or `test-mocha-casperjs\test\` on Windows.

**Comment by nathanboktae** [comment]
https://github.com/nathanboktae/mocha-casperjs#windows-users
