### ISSUE TITLE
Not working on windows 

### ISSUE THREAD

**Issue by mbhar6** [nathanboktae/mocha-casperjs#98]
Running "mocha_casperjs:files" (mocha_casperjs) task
The system cannot find the path specified.

**Comment by nathanboktae** [comment]
Sounds like you're using a grunt task that is not finding `mocha-casperjs.bat` which is all I distribute in this package. File an issue with whatever is wrapping the package or just directly use `mocha-casperja.bat`

**Comment by mbhar6** [comment]
Hi Nathan,

even if I, run mocha-casperjs individually , it still gives the same error on windows.
We have tried on multiple windows machine, but the issue persists.
Have a go at it in windows.
